version: '3.8'

# Configuración optimizada para producción

services:
  # PHP-FPM service
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: sboil_php
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
      - ./docker/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/conf.d/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - app_network
      - red_general
    environment:
      - APP_ENV=production
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Nginx service
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: sboil_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - nginx_cache:/var/cache/nginx
    networks:
      - app_network
    depends_on:
      - php
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Laravel Reverb WebSocket service
  reverb:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: sboil_reverb
    restart: always
    working_dir: /var/www/html
    ports:
      - "8080:8080"
    volumes:
      - ./app:/var/www/html
      - ./docker/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - app_network
      - red_general
    environment:
      - APP_ENV=production
    depends_on:
      - php
      - redis
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Queue Worker service con múltiples workers
  queue:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: sboil_queue
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
      - ./docker/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - app_network
      - red_general
    environment:
      - APP_ENV=production
    depends_on:
      - php
      - redis
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600 --memory=512
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Redis service para cache y sessions
  redis:
    image: redis:7-alpine
    container_name: sboil_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Scheduler service para Laravel Cron
  scheduler:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: sboil_scheduler
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
      - ./docker/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - app_network
      - red_general
    environment:
      - APP_ENV=production
    depends_on:
      - php
    command: sh -c "while true; do php artisan schedule:run; sleep 60; done"
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

networks:
  app_network:
    driver: bridge
  red_general:
    external: true

volumes:
  redis_data:
    driver: local
  nginx_cache:
    driver: local
