services:
  # Servicio unificado: PHP + Nginx + Node.js + Redis
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: webapp:latest
    container_name: ${APP_NAME:-superbasicos3}_app
    restart: unless-stopped
    working_dir: /var/www/html
    # Sin puertos expuestos - usar Nginx Proxy Manager
    # ports:
    #   - "80:80"     # Nginx (manejado por Nginx Proxy Manager)
    #   - "5173:5173" # Vite (solo para desarrollo local)
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/conf.d/laravel.conf:/etc/nginx/sites-available/default
      - ./docker/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/conf.d/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    networks:
      - app_network
      - red_general
    environment:
      - PHP_IDE_CONFIG=serverName=superbasicos3
      - NODE_ENV=development

networks:
  app_network:
    driver: bridge
  red_general:
    external: true
